---

- name: packages dependencies
  apt: >
    pkg={{ item }}
    state=present
    force=true
  with_items:
    - apt-transport-https
  sudo: yes

- name: packages undependencies
  apt: >
    pkg={{ item }}
    state=absent
    purge=yes
  with_items:
    - nodejs-legacy
  sudo: yes

- name: packages pinning
  template: >
    src=pinning.j2
    dest=/etc/apt/preferences.d/nodejs
  sudo: yes

- name: repositories key
  apt_key: >
    url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state=present
  sudo: yes

- name: repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb https://deb.nodesource.com/node {{ ansible_lsb.codename }} main
  sudo: yes

- name: packages
  apt: >
    pkg={{ item }}
    state=latest
  with_items:
    - nodejs
  sudo: yes
