---

- name: packages dependencies
  apt: >
    name={{ item }}
    state=present
    force=true
  with_items:
    - apt-transport-https
  sudo: yes

- name: packages undependencies
  apt: >
    name={{ item }}
    state=absent
    purge=yes
  with_items:
    - nodejs-legacy
  sudo: yes

- name: packages pinning
  template: >
    src=pinning.j2
    dest=/etc/apt/preferences.d/nodejs
  sudo: yes

- name: repositories key
  apt_key: >
    url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state=present
  sudo: yes

- name: repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb https://deb.nodesource.com/node {{ ansible_distribution_release }} main
  sudo: yes

- name: packages
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - nodejs
  sudo: yes

- name: packages npm
  npm: >
    name={{ item }}
    state=present
    global=yes
    version=2
  with_items:
    - npm
  sudo: yes

- name: sudo
  template: >
    src=node_env.j2
    dest=/etc/sudoers.d/node_env
  notify:
    - sudo restart
  sudo: yes
